import * as v from 'valibot'

export const postSchema = v.object({
  /**
   * Unique ID of the post
   * @default {Generated by database}
   */
  id: v.pipe(v.string(), v.uuid()),
  /**
   * Post content
   */
  //   post: v.string().min(1).max(140),
  post: v.pipe(v.string(), v.minLength(1), v.maxLength(140)),
  /**
   * Post createdAt
   */
  createdAt: v.date(),
  /**
   * Post updatedAt
   */
  updatedAt: v.date(),
})
